In [1]:
print("Hello")

Hello

In [2]:
from trading_ig import IGService

In [3]:
from trading_ig.rest import IGService
from trading_ig.config import config

In [4]:
ig_service = IGService(config.username, config.password, config.api_key)

In [7]:
ig = ig_service.create_session()

InvalidHeader: Header part (('fa51b09392954a22298b67d2dfd765cfeac8fe26',)) from ('X-IG-API-KEY', ('fa51b09392954a22298b67d2dfd765cfeac8fe26',)) must be of type str or bytes, not <class 'tuple'>

In [9]:
ig

{'accountType': 'SPREADBET',
 'accountInfo': {'balance': 9897.82,
  'deposit': 40.68,
  'profitLoss': -1.66,
  'available': 9855.48},
 'currencyIsoCode': 'GBP',
 'currencySymbol': '£',
 'currentAccountId': 'Z63VU2',
 'lightstreamerEndpoint': 'https://demo-apd.marketdatasystems.com',
 'accounts': [{'accountId': 'Z63VU1',
   'accountName': 'CFD',
   'preferred': False,
   'accountType': 'CFD'},
  {'accountId': 'Z63VU2',
   'accountName': 'Spread bet',
   'preferred': True,
   'accountType': 'SPREADBET'}],
 'clientId': '104491163',
 'timezoneOffset': 0,
 'hasActiveDemoAccounts': True,
 'hasActiveLiveAccounts': True,
 'trailingStopsEnabled': False,
 'reroutingEnvironment': None,
 'dealingEnabled': True}

In [10]:
accounts = ig_service.fetch_accounts()

In [11]:
accounts

,accountId,accountName,accountAlias,status,accountType,preferred,currency,canTransferFrom,canTransferTo,available,balance,deposit,profitLoss
0,Z63VU1,CFD,None,ENABLED,CFD,False,GBP,True,True,10491.54,10491.54,0.00,0.00
1,Z63VU2,Spread bet,None,ENABLED,SPREADBET,True,GBP,True,True,9855.45,9897.82,40.68,-1.69

In [14]:
accounts.accountId

0    Z63VU1
1    Z63VU2
Name: accountId, dtype: object

In [12]:
accounts.balance[0]

np.float64(10491.54)

In [18]:
account_info =  ig_service.fetch_accounts()

In [19]:
account_info

,accountId,accountName,accountAlias,status,accountType,preferred,currency,canTransferFrom,canTransferTo,available,balance,deposit,profitLoss
0,Z63VU1,CFD,None,ENABLED,CFD,False,GBP,True,True,10491.54,10491.54,0.00,0.00
1,Z63VU2,Spread bet,None,ENABLED,SPREADBET,True,GBP,True,True,9858.11,9897.82,40.82,1.11

In [23]:
balance =account_info.balance[0]

In [24]:
balance

np.float64(10491.54)

In [13]:
 market_info = ig_service.fetch_market_by_epic("CS.D.EURUSD.MINI.IP")

In [26]:
market_info

Munch({'instrument': Munch({'epic': 'CS.D.EURUSD.MINI.IP', 'expiry': '-', 'name': 'EUR/USD Mini', 'forceOpenAllowed': True, 'stopsLimitsAllowed': True, 'lotSize': 1.0, 'unit': 'AMOUNT', 'type': 'CURRENCIES', 'controlledRiskAllowed': True, 'streamingPricesAvailable': False, 'marketId': 'EURUSD', 'currencies': [Munch({'code': 'USD', 'symbol': '$', 'baseExchangeRate': 1.315624, 'exchangeRate': 0.66, 'isDefault': False})], 'sprintMarketsMinimumExpiryTime': None, 'sprintMarketsMaximumExpiryTime': None, 'marginDepositBands': [Munch({'min': 0, 'max': 578, 'margin': 3.33, 'currency': 'USD'}), Munch({'min': 578, 'max': 2890, 'margin': 3.33, 'currency': 'USD'}), Munch({'min': 2890, 'max': 4624, 'margin': 3.33, 'currency': 'USD'}), Munch({'min': 4624, 'max': None, 'margin': 15, 'currency': 'USD'})], 'marginFactor': 3.33, 'marginFactorUnit': 'PERCENTAGE', 'slippageFactor': Munch({'unit': 'pct', 'value': 50.0}), 'limitedRiskPremium': Munch({'value': 1.2, 'unit': 'POINTS'}), 'openingHours': None, 'expiryDetails': None, 'rolloverDetails': None, 'newsCode': 'EUR=', 'chartCode': 'EURUSD', 'country': None, 'valueOfOnePip': None, 'onePipMeans': None, 'contractSize': None, 'specialInfo': ['DEFAULT KNOCK OUT LEVEL DISTANCE', 'MIN KNOCK OUT LEVEL DISTANCE', 'MAX KNOCK OUT LEVEL DISTANCE']}), 'dealingRules': Munch({'minStepDistance': Munch({'unit': 'POINTS', 'value': 5.0}), 'minDealSize': Munch({'unit': 'POINTS', 'value': 0.04}), 'minControlledRiskStopDistance': Munch({'unit': 'POINTS', 'value': 5.0}), 'minNormalStopOrLimitDistance': Munch({'unit': 'POINTS', 'value': 2.0}), 'maxStopOrLimitDistance': Munch({'unit': 'PERCENTAGE', 'value': 75.0}), 'controlledRiskSpacing': Munch({'unit': 'POINTS', 'value': 20.0}), 'marketOrderPreference': 'AVAILABLE_DEFAULT_OFF', 'trailingStopsPreference': 'AVAILABLE'}), 'snapshot': Munch({'marketStatus': 'TRADEABLE', 'netChange': -0.2, 'percentageChange': 0, 'updateTime': '22:00:11', 'delayTime': 0, 'bid': 13050.8, 'offer': 13052.8, 'high': 13053.3, 'low': 13050.4, 'binaryOdds': None, 'decimalPlacesFactor': 1, 'scalingFactor': 1, 'controlledRiskExtraSpread': 2.4})})

In [ ]:
market_info

In [1]:
epic = "CCS.D.USCGC.TODAY.IP"

market_info = ig_service.fetch_market_by_epic(epic)

NameError: name 'ig_service' is not defined

In [21]:
test = market_info['snapshot']['bid']

In [22]:
test

13050.8